# Generated by Django 3.2 on 2022-08-29 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitCode', models.CharField(max_length=50)),
                ('unitLevel', models.CharField(max_length=50, null=True)),
                ('unitCredits', models.CharField(max_length=50, null=True)),
                ('unitName', models.CharField(max_length=200)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('unitCourse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rmsapp.course')),
            ],
        ),
    ]
