# Generated by Django 3.2 on 2022-08-29 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0002_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='units',
            old_name='unitCourse',
            new_name='Course',
        ),
    ]
