# Generated by Django 3.2 on 2022-08-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0003_rename_unitcourse_units_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='units',
            name='unitLevel',
            field=models.CharField(choices=[('4', '4'), ('5', '5'), ('6', '6')], max_length=50, null=True),
        ),
    ]
