# Generated by Django 3.2 on 2022-08-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0004_alter_units_unitlevel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='Unit',
        ),
    ]
