# Generated by Django 3.2 on 2022-08-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0005_rename_units_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='academicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=50)),
            ],
        ),
    ]
