# Generated by Django 3.2 on 2022-08-30 12:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0006_academicyear'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
