# Generated by Django 3.2 on 2022-08-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0007_academicyear_datecreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='Course',
            new_name='course',
        ),
    ]
