# Generated by Django 3.2 on 2022-09-03 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsapp', '0013_auto_20220903_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
